### ISSUE TITLE
gtk3?

### ISSUE THREAD

**Issue by gaydenko** [amozzhuhin/eclipse-hotkeys-fix#1]
Hi! Are there plans to support gtk3 also?

P.S. And really great thanks for the fix!

**Comment by amozzhuhin** [comment]
Hi, Andrew

Yes, I'm thinking about GTK3 support and will try to get close look on it soon.
Thank you, I'm glad to see that this fix is useful for you.

**Comment by gaydenko** [comment]
Great, thanks! Will we keep the issue opened till gtk3-version href will appear here?

**Comment by amozzhuhin** [comment]
Yep, will close this issue only on competition.

**Comment by gaydenko** [comment]
Great, thanks! Have quickly tried - it does work as expected.
